### ISSUE TITLE
RepeatVector and TimeDistributed unsupported keras layers in HLS4ML

### ISSUE THREAD

**Issue by yinLX19** [walkieq/RNN_HLS#1]
Hi!

I want to implement an LSTM Autoencoder on FPGA for anomaly detection. I need to do that automatically from python deep learning libraries. The problem is, the RepeatVector and TimeDistributed keras layers are actually not supported by HLS4ML. How can I integrate that in Vivado HLS?

Thanks in advance!
Sami

**Comment by walkieq** [comment]
Hi Sami 

You can find the RepeatVector funciton implemented in my example, which is at line 20 of 
https://github.com/walkieq/RNN_HLS/blob/main/lstm_ae_small/lstm.cpp

The TimeDistributed layer is a little tricky. I met some timing and resource issues when I implmeneted it as a individually function like RepeatVector. Finally, it is intergated to the previous layer. In the lstm example,  it is combined with the previous LSTM layer. The combined function can be found at the line 78 of 
https://github.com/walkieq/RNN_HLS/blob/main/lstm_ae_small/lstm.cpp


Best, 
Zhiqiang (Walkie)

**Comment by walkieq** [comment]
Hi Sami

You can find the RepeatVector function implemented in my example, which is at line 20 of
https://github.com/walkieq/RNN_HLS/blob/main/lstm_ae_small/lstm.cpp

The TimeDistributed layer is a little tricky. I met some timing and resource issues when I implemented it as an individual function like RepeatVector. Finally, it is integrated into the previous layer. In the lstm example, it is combined with the previous LSTM layer. The combined function can be found at the line 78 of
https://github.com/walkieq/RNN_HLS/blob/main/lstm_ae_small/lstm.cpp

Best,
Zhiqiang (Walkie)


> 
> 
> Hi!
> 
> I want to implement an LSTM Autoencoder on FPGA for anomaly detection. I need to do that automatically from python deep learning libraries. The problem is, the RepeatVector and TimeDistributed keras layers are actually not supported by HLS4ML. How can I integrate that in Vivado HLS?
> 
> Thanks in advance! Sami

**Comment by yinLX19** [comment]
Hi Walkie!

Thanks for your reply, I'll see how I can integrate your solution into my design and how I can make it automatic from Keras.

Best Regards,
Sami
