### ISSUE TITLE
partitioned elements number (4096) has exeeded the threshold (1024)

### ISSUE THREAD

**Issue by XS30** [walkieq/RNN_HLS#2]
Hi,

I try to use Vivado HLS 2021 to synthesis the project, but it prints “ERROR: [XFORM 203-103] Array 'mult.V' (././nnet_utils/nnet_dense.h:60): partitioned elements number (4096) has exeeded the threshold (1024), which may cause long run-time.”
I try to find out this question when saw other web, but Vivado HLS soft version solution settings did not find the "add command option".
Thank you.

**Comment by walkieq** [comment]
Hi, 

Thanks for trying this template. 
You can find the solution at the end of the description of the Example1 in the README page. 

I also copy it here for your quick reference. 
It requires to set the maximum_size of the config_array_partition to be 4096.
1) Right click the Solution name and choose "Solution Setting..."
2) In the General, choose "Add..."
3) In the command:, choose config_array_partition
4) Change the maximum_size from 1024 to 4096 and remove all the other numbers.

Hope you have a nice holiday!

**Comment by XS30** [comment]
Thank you for your reply

I use Vivado HLS 2021 to synthesis the project, but it is not "Add..." or other options
As shown in the figure. 

 Thank you


 

![1640830677(1)](https://user-images.githubusercontent.com/51533985/147716473-b9f6bcde-8bc3-4f40-a51b-da283bffa23a.jpg)

**Comment by XS30** [comment]
Maybe I need to install a  low version Vivado to synthesis the project.

**Comment by XS30** [comment]
I read the hls4ml online help documentation. This problem is caused by my software version. Because 2020.2 have not Vivado hls only Vitis hls.
Hope you have a nice holiday!

**Comment by walkieq** [comment]
Yeah. The Vitis_HLS and Vivado_HLS are not fully compatible.
