### ISSUE TITLE
Weight size of lstm1_wx and lstm1_wh

### ISSUE THREAD

**Issue by chuliang007** [walkieq/RNN_HLS#5]
Dear @walkieq,

Thanks for making the code open-source. For your 1-layer LSTM example, it prints lstm1_wx in a shape of [N1_LX][N1_LX][N1_LH * 4] = 28 * 28 * 32 * 4 in PyTorch as each feature of the input has a set of network parameters. While you set the lstm1_wx in the shape of [N1_LX][N1_LH * 4], which is much smaller than the weight should be.

Is there anything wrong with my understanding? Looking forward to your reply and thanks in advance.

**Comment by walkieq** [comment]
Generally, the weights in each time step are the same for LSTMs. Thus the timestep (same to N1_LX in this example) would not affect the size of weight matrix. Would you like to have a check?

**Comment by chuliang007** [comment]
Thanks for your reply. In PyTorch with an example LSTM with 10 timesteps, 160 features, and 100 hidden units, the lstm1_wx is in a shape of [N1_LX][N1_LX][N1_LH * 4] = [160][160][400], and the lstm1_wh is in a shape of [N1_LX][N1_LH][N1_LH * 4] = [160][100][400]. They are actually different for each feature of the input:

networks.158.lstm.weight_ih_l0 torch.Size([400, 160]) tensor([[ 0.0031,  0.0010,  0.0176,  ...,  0.0413,  0.0311,  0.0470],
        [ 0.0825,  0.0047, -0.0777,  ..., -0.0884, -0.0169, -0.0210],
        [-0.0856,  0.0619, -0.0542,  ...,  0.0918, -0.0872,  0.0103],
        ...,
        [-0.0379, -0.0452,  0.0025,  ...,  0.0420, -0.0154,  0.0163],
        [ 0.0373,  0.0495,  0.0050,  ..., -0.0329, -0.0827,  0.0189],
        [-0.0839, -0.0737, -0.0346,  ...,  0.0870,  0.0161,  0.0808]])
networks.158.lstm.weight_hh_l0 torch.Size([400, 100]) tensor([[ 0.0239, -0.0925,  0.0097,  ..., -0.0986,  0.0585,  0.0010],
        [ 0.0867,  0.0943, -0.0048,  ..., -0.0197,  0.0264,  0.0035],
        [ 0.0948, -0.0477,  0.0755,  ..., -0.0336, -0.0249, -0.0667],
        ...,
        [ 0.0474, -0.0323, -0.0785,  ...,  0.0761,  0.0220, -0.0877],
        [ 0.0490, -0.0789,  0.0137,  ..., -0.0155,  0.0430,  0.0930],
        [-0.0342, -0.0836, -0.0054,  ...,  0.0850,  0.0270, -0.0406]])


networks.159.lstm.weight_ih_l0 torch.Size([400, 160]) tensor([[ 0.0044,  0.0917,  0.0021,  ..., -0.0083,  0.0220,  0.0370],
        [ 0.0659,  0.0248,  0.0542,  ..., -0.0058, -0.0592, -0.0981],
        [-0.0452,  0.0321,  0.0344,  ...,  0.0854,  0.0271, -0.0119],
        ...,
        [-0.0178, -0.0065, -0.0328,  ..., -0.0500, -0.0276,  0.0948],
        [ 0.0496,  0.0097,  0.0928,  ...,  0.0234, -0.0673, -0.0355],
        [ 0.0366, -0.0835, -0.0137,  ..., -0.0756, -0.0246, -0.0014]])
networks.159.lstm.weight_hh_l0 torch.Size([400, 100]) tensor([[-0.0998,  0.0901,  0.0552,  ...,  0.0990,  0.0291,  0.0675],
        [ 0.0429, -0.0973, -0.0838,  ...,  0.0506, -0.0662,  0.0459],
        [-0.0938,  0.0622,  0.0056,  ..., -0.0213,  0.0509, -0.0886],
        ...,
        [ 0.0276, -0.0652,  0.0963,  ...,  0.0720, -0.0275,  0.0384],
        [-0.0434,  0.0700,  0.0246,  ...,  0.0534,  0.0085,  0.0645],
        [-0.0421,  0.0640,  0.0752,  ..., -0.0095, -0.0446, -0.0034]])

**Comment by walkieq** [comment]
It does not look correct to me that the weight matrix is a 3D matrix. 

I have tried an LSTM example using your parameters in PyTorch. It looks like this as follows. The size of weight is (400, 100) for Wh and (400, 160) for Wx: 


#> lstm = torch.nn.LSTM(160, 100)
#> input = torch.randn(10,160)
#> output, (hn, cn) = lstm(input)

#> print(output.size())
torch.Size([10, 100])

#> print(hn.size())
torch.Size([1, 100])
#> print(lstm.weight_ih_l0.size())
torch.Size([400, 160])
#> print(lstm.weight_hh_l0.size())
torch.Size([400, 100])
#>

**Comment by chuliang007** [comment]
Thanks for your kind reply, and you are correct.
