### ISSUE TITLE
About the LSTM MNIST results

### ISSUE THREAD

**Issue by newfrogg** [walkieq/RNN_HLS#8]
Not really an issue, but I want to know the performance of LSTM layers under using HSL4ML framework. Did you take it any papers ? I want to reference them. Thanks.

**Comment by walkieq** [comment]
Hi, 

It is created by myself. If you are happy, please cite this repository with DOI. 
[1] Zhiqiang Que, “walkieq/RNN_HLS: RNN_HLS_v0.5”. Zenodo, 2024. doi: 10.5281/zenodo.11112775.

**Comment by newfrogg** [comment]
Hi @walkieq, did you publish this paper. If possible, I would like to read it more. I'm working to test LSTM using MNIST. Thanks

**Comment by walkieq** [comment]
> Hi @walkieq, did you publish this paper. If possible, I would like to read it more. I'm working to test LSTM using MNIST. Thanks

No, I have not published it yet.

**Comment by newfrogg** [comment]
OK, I see. Looking forward for your publish. Thanks.

**Comment by walkieq** [comment]
> OK, I see. Looking forward for your publish. Thanks.

Cheers!
